
name: Build and run simple unit test(s) on pull request v2

on:
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  run_unit_test_suites_v2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install gcovr
      run: pip install gcovr
    
    - name: Run test suites and generate code coverage report
      working-directory: ${{github.workspace}}
      run: ls
      run: ./test_coverage

