
name: Build and run simple unit test(s) on pull request v2

on:
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  run_unit_test_suites_v2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install gcovr
      run: pip install gcovr
    
    - name: Install gnuplot
      run: | 
        sudo apt-get install gnuplot
    
    - name: Run test suites and generate code coverage report
      working-directory: ${{github.workspace}}
      run: |
        rm -rf build
        mkdir build
        cd build/
        cmake .. -DCMAKE_BUILD_TYPE=DEBUG
        cmake --build .
        ./Satellite_tests
        ./utils_tests
        gcovr -r .. --filter ../src/ --filter ../include/ --json-summary ../test_coverage_summary_actions_generated.json
        cd ${{github.workspace}}
        rm ${{github.workspace}}/test_plot.png
    - uses: actions/upload-artifact@v4
      with:
        name: test_coverage_artifact
        path: ${{github.workspace}}/test_coverage_summary_actions_generated.json

