
name: Build and run tests on pull request v2

on:
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  run_unit_test_suites_v2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install gnuplot
      run: sudo apt-get install gnuplot
        
    - name: Run test suites
      working-directory: ${{github.workspace}}
      run: |
        rm -rf build
        mkdir build
        cd build/
        cmake .. -DCMAKE_BUILD_TYPE=RELEASE
        cmake --build .
        ./Satellite_tests
        ./utils_tests
        cd ..
        rm test_plot.png

    
